### ISSUE TITLE
Pure dynamic analysis , no symbolic states

### ISSUE THREAD

**Issue by nguyenthanhvuh** [unsat/dig#10]
Ability to run using pure dynamic analysis (i.e., automatically generate inputs). Not requiring symbolic traces.

Add these results for the programs that cannot use symbolic execution (e.g., those with doubles freire2 etc)

**Comment by nguyenthanhvuh** [comment]
done, in 5d29160eee450558127c079d6e98e01be0370091

**Comment by TaihuLight** [comment]
@nguyenthanhvuh 
The newly updated DIG cannot generate trace for infer invariants from C program (e.g.  https://github.com/unsat/dig/issues/24). When I run the command `sage -python -O dig.py bench17_potsumm2.c -log 3`, DIG outputs the following result:
```
ly@INV:~/dig/src$ sage -python -O dig.py bench17_potsumm2.c -log 3
settings:INFO:2021-08-14 13:23:56.434022: dig.py bench17_potsumm2.c -log 3
alg:INFO:analyze 'bench17_potsumm2.c'
alg:INFO:compute symbolic states (4.60s)
alg:WARNING:vtrace: I x, I y: no symbolic states. Skip
alg:INFO:infer invs at 0 locs: 
Traceback (most recent call last):
  File "dig.py", line 252, in <module>
    dig.start(seed=seed, maxdeg=args.maxdeg)
  File "/home/ly/dig/src/alg.py", line 139, in start
    self.infer(self.EQTS, dinvs,
  File "/home/ly/dig/src/alg.py", line 200, in infer
    new_invs = f()  # get invs
  File "/home/ly/dig/src/alg.py", line 140, in <lambda>
    lambda: self.infer_eqts(maxdeg, dtraces, inps))
  File "/home/ly/dig/src/alg.py", line 217, in infer_eqts
    auto_deg = self.get_auto_deg(maxdeg)
  File "/home/ly/dig/src/alg.py", line 46, in get_auto_deg
    maxvars = max(self.inv_decls.values(), key=lambda d: len(d))
ValueError: max() arg is an empty sequence

```
Is there a bug that causes this problem for the recently updated DIG?
