### ISSUE TITLE
AttributeError exception

### ISSUE THREAD

**Issue by letonchanh** [unsat/dig#21]
Hi,

I have this problem when running Dig

```
sage -python -O src/dig.py tests/traces/CohenDiv.tcs 
Traceback (most recent call last):
  File "src/dig.py", line 239, in <module>
    dig.start(seed=seed, maxdeg=args.maxdeg)
  File "/tools/dig/src/alg.py", line 321, in start
    wrs = CM.run_mp("(pure) dynamic inference", tasks, f, settings.DO_MP)
AttributeError: module 'helpers.vcommon' has no attribute 'run_mp'
```

**Comment by nguyenthanhvuh** [comment]
Thanks, Chanh.  just fixed the issue with commit https://github.com/unsat/dig/commit/534508201e441975b2088ad79a892fc3de152bb0
