### ISSUE TITLE
How to generate invariants for C programs with array variables?

### ISSUE THREAD

**Issue by TaihuLight** [unsat/dig#23]
How to fix the following program  with an array variable in order to generate the invariants for it?
```
#include <stdio.h>
#include <stdlib.h>

void vassume(int b){}
void vtrace1(int * a, int h, int n, int c, int k, int m){} 

void mainQ(int a[], int h){ 
  int n = 0;
  int c = 0;
  int k = 1;
  int m = 6;
  while(n < h)
  // invariant 0 <= n <= a.Length
  // invariant forall i :: 0 <= i < n ==> a[i] == i*i*i
  // invariant c == n*n*n
  // invariant k == 3*n*n + 3*n + 1
  // invariant m == 6*n + 6
  {
    vtrace1(a, h, n, c, k, m);
    a[n] = c;
    c = c + k;
    k = k + m;
    m = m + 6;
    n = n + 1;
  }
  //postcondition 
  //assert(0 <= i < n && a[i] == i*i*i);
}


void main(int argc, char **argv){
    mainQ(atoi(argv[1]), atoi(argv[2]));
}
```

When I run the command ``` sage -python -O dig.py bench15_Cubes3.c -log 4 -nominmax -nominmaxplus -nomp -maxdeg 2 -seed 0 ```, it occurs the errors:
```
bench15_Cubes3.c:33:11: warning: passing argument 1 of ‘mainQ’ makes pointer from integer without a cast [-Wint-conversion]
   33 |     mainQ(atoi(argv[1]), atoi(argv[2]));
      |           ^~~~~~~~~~~~~
      |           |
      |           int
bench15_Cubes3.c:8:16: note: expected ‘int *’ but argument is of type ‘int’
    8 | void mainQ(int a[], int h){
      |            ~~~~^~~
/var/tmp/dig_0_83go_tf1/delete_me/traces/bench15_Cubes3.c: In function ‘vtrace1’:
/var/tmp/dig_0_83go_tf1/delete_me/traces/bench15_Cubes3.c:586:21: warning: format ‘%g’ expects argument of type ‘double’, but argument 2 has type ‘int *’ [-Wformat=]
  586 |   printf("vtrace1: %g %d %d %d %d %d\n", a, h, n, c, k, m);
      |                    ~^                    ~
      |                     |                    |
      |                     double               int *
      |                    %ls
/var/tmp/dig_0_83go_tf1/delete_me/traces/bench15_Cubes3.c: In function ‘main’:
/var/tmp/dig_0_83go_tf1/delete_me/traces/bench15_Cubes3.c:622:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  622 |   mainQ((int *)tmp___0, tmp);
      |         ^
```

**Comment by nguyenthanhvuh** [comment]
DIG focuses mainly on numerical programs and numerical invariants.  So it will not work with this program.  If you use some integer variable instead of array, it will work.

**Comment by TaihuLight** [comment]
@nguyenthanhvuh 
Can I generate trace file for this program, and then use DIG to infer invariants from the generated traces?
BTW, How to generate the trace file (e.g., ../test/traces/CohenDiv.tcs) as shown in the directory https://github.com/Kylin-PHYTIUM/dig-unsat/tree/main/tests/traces ?

**Comment by nguyenthanhvuh** [comment]
You can generate trace files for any program.  You can just use printf or some other method to print out (integer) values.  See the `CohenDiv.tcs` file for example.  

And yes, that version of DIG in the TOSEM paper can infer invariants, but this version does not.  The reason is this version involves symbolic execution for checking, whereas the TOSEM one is purely dynamic.

**Comment by TaihuLight** [comment]
@nguyenthanhvuh 
Is the version of DIG in the TOSEM paper aviable? If yes, where can I get it ?

**Comment by nguyenthanhvuh** [comment]
It is in the old directory https://github.com/unsat/dig/tree/dev/old/dig1.   But note that this was written back in 2013, so you will need  old versions of Sage and Python (2.x) for it to work.

**Comment by TaihuLight** [comment]
@nguyenthanhvuh  Does ```old/dig1``` support invariant generation for C programs?

**Comment by nguyenthanhvuh** [comment]
(1) DIG1 is pure dynamic so it is language agnostic.  The input is not a program but a trace file.  
(2) You can, by reimplementing the algorithm in `old/dig1` into DIG3.  But I think it would take some effort because you would also need to learn DIG3 implementation.  Probably it's easier to read the paper and reimplement the algorithm yourself and also reuse the code from `old/dig1` .

**Comment by TaihuLight** [comment]
To run `old/dig1`, which version of python 2.* and OS is recommond for me?

**Comment by nguyenthanhvuh** [comment]
It's a freely tropical library for computing the convex hulls of max/min-plus polyhedra. It doesn't seem to exist anymore. You don't need this to infer normal polynomial invariants.

**Comment by TaihuLight** [comment]
@nguyenthanhvuh 
Thank you very much.
According to the link of tplib, I also found its author's personal website and the install method of tplib, which is shown in [http://www.cmap.polytechnique.fr/~allamigeon/software/](url)

**Comment by TaihuLight** [comment]
BUGS
(1) Waring in miscs.py: `DeprecationWarning: CartesianProduct is deprecated. Use cartesian_product instead
See http://trac.sagemath.org/18411 for details.`  line 1310 and line 2034
```
#combs = CartesianProduct(*children)    
combs = cartesian_product(list(*children))

#idxs = CartesianProduct(*alists).list()
idxs =  cartesian_product(list(*alists)).list()
```

**Comment by nguyenthanhvuh** [comment]
is this for the old Dig code?  if so then it is expected that many things are outdated as it has been written almost 10 years ago.

**Comment by TaihuLight** [comment]
@nguyenthanhvuh 
I are fixing DIG1 to use it as a comparison method in my paper. Unfortunately, the trace files used in your paper are missing in this repository, could you provide the trace files and their programs used in your TOSEM paper? Especially, the trace files for generate array invariants are more crucial for me.
The fixed DIG1 is [dig-dev20210706.tar.gz](https://github.com/unsat/dig/files/6773901/dig-dev20210706.tar.gz)

**Comment by nguyenthanhvuh** [comment]
You can find many trace files from the TOSEM paper here https://github.com/unsat/dig/tree/dev/old/traces/AES_tosem.

**Comment by nguyenthanhvuh** [comment]
If you want, you can tell me the invariants your method can infer and I'll be happy tell you if DIG1 can infer them or not.  If not, then that save you time in trying to get DIG1 to work again.

 In general if they are of the form given in the TOSEM paper, then DIG1 can likely infer them, otherwise, it will not.  In particular, if *inequalities* are involved in the array, then DIG1 cannot infer them.

**Comment by TaihuLight** [comment]
Two C programs are showed as the following. Their invariants are needed to be inferred with DIG1. Can DIG1 infer them?

Program 1
```
#include <stdio.h>
#include <stdlib.h>

void mainQ(int a[], int h){
  int n = 0;
  int c = 0;
  int k = 1;
  int m = 6;
  while(n < h)
  {
    printf("[%d,%d] %d %d %d %d\n", a[n], n, c, k, m, h);
    a[n] = c;
    c = c + k;
    k = k + m;
    m = m + 6;
    n = n + 1;
  }
}

int main(void){
    int sz = 16;
    int randAr[sz] = {15,12,23,41,11,20,33,26,17,29,31,46,18,22,36,28};
    mainQ(randAr, 19);
    return EXIT_SUCCESS;
}
```
Generated trace files is 
```
a  n c k m h
[15,0] 0 1 6 16
[12,1] 1 7 12 16
[23,2] 8 19 18 16
[41,3] 27 37 24 16
[11,4] 64 61 30 16
[20,5] 125 91 36 16
[33,6] 216 127 42 16
[26,7] 343 169 48 16
[17,8] 512 217 54 16
[29,9] 729 271 60 16
[31,10] 1000 331 66 16
[46,11] 1331 397 72 16
[18,12] 1728 469 78 16
[22,13] 2197 547 84 16
[36,14] 2744 631 90 16
[28,15] 3375 721 96 16
```
Then, the error is shown as following when I run the command `sage -python dig_benchmark.py` to generate invariants on the above trace file with DIG1.

```
********** Generate invariants with DIG1 **********
Trace file: './trace/15Cubes.tcs'
seed: 0, maxdeg: 3
********** *************** **********

dig:Info:DIG (Dynamic Invariant Generator)
16:09:16, SageMath version 7.5.1, Release Date: 2017-01-15, chengzi Linux 4.15.0-142-generic x86_64
dig_miscs:Debug:Read Info:
0. filename: ./trace/15Cubes.tcs
1. ss_arr: [a]
2. ss_num: [c, k, m, n]
3. |tcs_arr|: 16
4. |tcs_num|: 16
5. xinfo: 
 0. All: ['a', 'c', 'k', 'm', 'n']
 1. Assume: []
 2. Const: []
 3. Expect: []
 4. ExtFun: []
 5. |ExtVar|: 0
 6. Global: []
 7. Input: []
 8. Output: []
dig:Debug:Set seed to: 0
dig:Debug:*** Generate Array Invs over [a] ***
dig:Info:*** FlatArray ***
dig:Debug:|terms|=0, |tcs|=16
dig:Info:Select traces
dig:Info:Compute invs over 16 tcs
dig_arrays:Info:Compute new traces (treating array elems as new vars)
[{a: [15, 0]}, {a: [12, 1]}, {a: [23, 2]}, {a: [41, 3]}, {a: [11, 4]}, {a: [20, 5]}, {a: [33, 6]}, {a: [26, 7]}, {a: [17, 8]}, {a: [29, 9]}, {a: [31, 10]}, {a: [46, 11]}, {a: [18, 12]}, {a: [22, 13]}, {a: [36, 14]}, {a: [28, 15]}]
dig_arrays:Debug:Find linear eqts over 2 array elems
dig:Info:*** Eqt ***
dig:Debug:|terms|=3, |tcs|=16
dig_arrays:Info:Select traces (note: |tcs|=|terms|=3)
dig_miscs:Debug:Total traces 16, request (ntcs 3, ntcs_extra 200)
dig_miscs:Debug:mk_traces: |tcs1|=3, |tcs2|=13 
dig:Info:Compute invs over 3 tcs
......
  File "/home/chengzi/workspace/dig1-dev/dig_polynomials.py", line 39, in solve
    sols = Miscs.solve_eqts(ts=self.terms, rv=0, ds=self.tcs)
  File "/home/chengzi/workspace/dig1-dev/dig_miscs.py", line 762, in solve_eqts
    eqts = Miscs.instantiate_template(template, tcs=ds)
  File "/home/chengzi/workspace/dig1-dev/dig_miscs.py", line 722, in instantiate_template
    eqts = [template.subs(tc) for tc in tcs]
TypeError: Argument 'd2' has incorrect type (expected dict, got OrderedDict)
```
BTW, the current version of DIG1 can infer equality and inequality invariants on the trace file './Examples/t1.tcs'. The obtained invariants are 
```
dig:Info:DIG (Dynamic Invariant Generator)
16:28:51, SageMath version 7.5.1, Release Date: 2017-01-15, chengzi Linux 4.15.0-142-generic x86_64
dig_miscs:Debug:Read Info:
0. filename: ./Examples/t1.tcs
1. ss_arr: []
2. ss_num: [x, y]
3. |tcs_arr|: 0
4. |tcs_num|: 6
5. xinfo: 
 0. All: ['x', 'y']
 1. Assume: [y >= x]
 2. Const: []
 3. Expect: ['2*x + 1 >= y']
 4. ExtFun: []
 5. |ExtVar|: 0
 6. Global: []
 7. Input: []
 8. Output: []
dig:Debug:Set seed to: 0
dig:Debug:*** Generate Polynomial Invs over [x, y] ***
dig:Debug:deg=2, |ss_num|=2, |terms|=6
dig:Info:*** Eqt ***
dig:Debug:|terms|=6, |tcs|=6
dig:Info:Select traces
dig_miscs:Debug:Total traces 6, request (ntcs 9, ntcs_extra 200)
dig_miscs:Debug:mk_traces: |tcs1|=6, |tcs2|=0 
dig:Info:Compute invs over 6 tcs
dig_miscs:Debug:Solve 6 (uniq) eqts for 6 unknowns
dig:Info:Refine 3 invs
refine:Debug:rfilter skips (|ps|=3, |tcs|=0)
refine:Debug:rinfer(|ps|=3)
refine:Debug:rinfer (before 3, after 1, diff 2)
dig:Info:Detected 1 invs for Eqt:
    0: 2*x - y + 1 == 0
dig:Info:*** IeqDeduce ***
dig:Debug:|terms|=0, |tcs|=0
dig_polynomials:Debug:|assumes|=1, |eqts|=1
dig_polynomials:Debug:* deduce(|assumes|=1,|eqts|=1)
dig_polynomials:Debug:assumed ps: -x + y >= 0
dig:Info:Detected 2 invs for IeqDeduce:
    0: x + 1 >= 0
    1: 1/2*y + 1/2 >= 0
Generated time: 1.464
```
Therefore, how to fix the current DIG1  in order to remove the errors and infer invariants for C Programs.
[Uploading dig1-fix20210706.tar.gz…]()

**Comment by TaihuLight** [comment]
Two C programs are showed as the following. Their invariants are needed to be inferred with DIG1. Can DIG1 infer them?

Program 1
```
#include <stdio.h>
#include <stdlib.h>

void mainQ(int a[], int h){
  int n = 0;
  int c = 0;
  int k = 1;
  int m = 6;
  while(n < h)
  {
    printf("[%d,%d] %d %d %d %d\n", a[n], n, c, k, m, h);
    a[n] = c;
    c = c + k;
    k = k + m;
    m = m + 6;
    n = n + 1;
  }
}

int main(void){
    int sz = 16;
    int randAr[sz] = {15,12,23,41,11,20,33,26,17,29,31,46,18,22,36,28};
    mainQ(randAr, 19);
    return EXIT_SUCCESS;
}
```
Generated trace files is 
```
a  n c k m h
[15,0] 0 1 6 16
[12,1] 1 7 12 16
[23,2] 8 19 18 16
[41,3] 27 37 24 16
[11,4] 64 61 30 16
[20,5] 125 91 36 16
[33,6] 216 127 42 16
[26,7] 343 169 48 16
[17,8] 512 217 54 16
[29,9] 729 271 60 16
[31,10] 1000 331 66 16
[46,11] 1331 397 72 16
[18,12] 1728 469 78 16
[22,13] 2197 547 84 16
[36,14] 2744 631 90 16
[28,15] 3375 721 96 16
```
Then, the error is shown as following when I run the command `sage -python dig_benchmark.py` to generate invariants on the above trace file with DIG1.

```
********** Generate invariants with DIG1 **********
Trace file: './trace/15Cubes.tcs'
seed: 0, maxdeg: 3
********** *************** **********

dig:Info:DIG (Dynamic Invariant Generator)
16:09:16, SageMath version 7.5.1, Release Date: 2017-01-15, chengzi Linux 4.15.0-142-generic x86_64
dig_miscs:Debug:Read Info:
0. filename: ./trace/15Cubes.tcs
1. ss_arr: [a]
2. ss_num: [c, k, m, n]
3. |tcs_arr|: 16
4. |tcs_num|: 16
5. xinfo: 
 0. All: ['a', 'c', 'k', 'm', 'n']
 1. Assume: []
 2. Const: []
 3. Expect: []
 4. ExtFun: []
 5. |ExtVar|: 0
 6. Global: []
 7. Input: []
 8. Output: []
dig:Debug:Set seed to: 0
dig:Debug:*** Generate Array Invs over [a] ***
dig:Info:*** FlatArray ***
dig:Debug:|terms|=0, |tcs|=16
dig:Info:Select traces
dig:Info:Compute invs over 16 tcs
dig_arrays:Info:Compute new traces (treating array elems as new vars)
[{a: [15, 0]}, {a: [12, 1]}, {a: [23, 2]}, {a: [41, 3]}, {a: [11, 4]}, {a: [20, 5]}, {a: [33, 6]}, {a: [26, 7]}, {a: [17, 8]}, {a: [29, 9]}, {a: [31, 10]}, {a: [46, 11]}, {a: [18, 12]}, {a: [22, 13]}, {a: [36, 14]}, {a: [28, 15]}]
dig_arrays:Debug:Find linear eqts over 2 array elems
dig:Info:*** Eqt ***
dig:Debug:|terms|=3, |tcs|=16
dig_arrays:Info:Select traces (note: |tcs|=|terms|=3)
dig_miscs:Debug:Total traces 16, request (ntcs 3, ntcs_extra 200)
dig_miscs:Debug:mk_traces: |tcs1|=3, |tcs2|=13 
dig:Info:Compute invs over 3 tcs
......
  File "/home/chengzi/workspace/dig1-dev/dig_polynomials.py", line 39, in solve
    sols = Miscs.solve_eqts(ts=self.terms, rv=0, ds=self.tcs)
  File "/home/chengzi/workspace/dig1-dev/dig_miscs.py", line 762, in solve_eqts
    eqts = Miscs.instantiate_template(template, tcs=ds)
  File "/home/chengzi/workspace/dig1-dev/dig_miscs.py", line 722, in instantiate_template
    eqts = [template.subs(tc) for tc in tcs]
TypeError: Argument 'd2' has incorrect type (expected dict, got OrderedDict)
```
BTW, the current version of DIG1 can infer equality and inequality invariants on the trace file './Examples/t1.tcs'. The obtained invariants are 
```
dig:Info:DIG (Dynamic Invariant Generator)
16:28:51, SageMath version 7.5.1, Release Date: 2017-01-15, chengzi Linux 4.15.0-142-generic x86_64
dig_miscs:Debug:Read Info:
0. filename: ./Examples/t1.tcs
1. ss_arr: []
2. ss_num: [x, y]
3. |tcs_arr|: 0
4. |tcs_num|: 6
5. xinfo: 
 0. All: ['x', 'y']
 1. Assume: [y >= x]
 2. Const: []
 3. Expect: ['2*x + 1 >= y']
 4. ExtFun: []
 5. |ExtVar|: 0
 6. Global: []
 7. Input: []
 8. Output: []
dig:Debug:Set seed to: 0
dig:Debug:*** Generate Polynomial Invs over [x, y] ***
dig:Debug:deg=2, |ss_num|=2, |terms|=6
dig:Info:*** Eqt ***
dig:Debug:|terms|=6, |tcs|=6
dig:Info:Select traces
dig_miscs:Debug:Total traces 6, request (ntcs 9, ntcs_extra 200)
dig_miscs:Debug:mk_traces: |tcs1|=6, |tcs2|=0 
dig:Info:Compute invs over 6 tcs
dig_miscs:Debug:Solve 6 (uniq) eqts for 6 unknowns
dig:Info:Refine 3 invs
refine:Debug:rfilter skips (|ps|=3, |tcs|=0)
refine:Debug:rinfer(|ps|=3)
refine:Debug:rinfer (before 3, after 1, diff 2)
dig:Info:Detected 1 invs for Eqt:
    0: 2*x - y + 1 == 0
dig:Info:*** IeqDeduce ***
dig:Debug:|terms|=0, |tcs|=0
dig_polynomials:Debug:|assumes|=1, |eqts|=1
dig_polynomials:Debug:* deduce(|assumes|=1,|eqts|=1)
dig_polynomials:Debug:assumed ps: -x + y >= 0
dig:Info:Detected 2 invs for IeqDeduce:
    0: x + 1 >= 0
    1: 1/2*y + 1/2 >= 0
Generated time: 1.464
```
Therefore, how to fix the current DIG1  in order to remove the errors and infer invariants for C Programs.

**Comment by nguyenthanhvuh** [comment]
I won't have too much time to debug DIG1, which has been written too long ago.   Most likely it will have errors as newer Sage,Python has different API's (in fact, I am surprised you got it some of it to work). So you just have to hack it yourself.    With that said, it seems the error you have is just some simple type error.  May be the `tc` passed in to `subs` should be a dict instead of OrderedDict.  It could be that `subs` being stricter that what it is used to be.

**Comment by TaihuLight** [comment]
The C program is shown as the following. The invariants are needed to be inferred with DIG1. Can DIG1 infer this C program?
```
#include <stdio.h>
#include <stdlib.h>

void mainQ(int a[], int h){
  int n = 0;
  int c = 0;
  int k = 1;
  int m = 6;
  while(n < h)
  {
    printf("[%d,%d] %d %d %d %d\n", a[n], n, c, k, m, h);  #generate traces
    a[n] = c;
    c = c + k;
    k = k + m;
    m = m + 6;
    n = n + 1;
  }
}

int main(void){
    int sz = 16;
    int randAr[sz] = {15,12,23,41,11,20,33,26,17,29,31,46,18,22,36,28};
    mainQ(randAr, 19);
    return EXIT_SUCCESS;
}
```
Generated trace files is [15Cubes.tcs.txt](https://github.com/unsat/dig/files/6794929/15Cubes.tcs.txt), i.e.,
```
[15,0] 0 1 6 16
[12,1] 1 7 12 16
[23,2] 8 19 18 16
[41,3] 27 37 24 16
[11,4] 64 61 30 16
[20,5] 125 91 36 16
[33,6] 216 127 42 16
[26,7] 343 169 48 16
[17,8] 512 217 54 16
[29,9] 729 271 60 16
[31,10] 1000 331 66 16
[46,11] 1331 397 72 16
[18,12] 1728 469 78 16
[22,13] 2197 547 84 16
[36,14] 2744 631 90 16
[28,15] 3375 721 96 16
```

@nguyenthanhvuh  
(1) Is the generated trace file correct for the above C program?
(2) Can DIG1 infer array invariants for the above C Program?

**Comment by nguyenthanhvuh** [comment]
1. do you mean the *format* is correct?  if so ,  yes.  Otherwise I don't understand what you mean by "correct for your C program".
2. by looking at the traces, I can't tell if there are any array invariants.  What invariants do you expect?

**Comment by TaihuLight** [comment]
2. The expected Invariants are 
```
a[n]=n*n*n
c=n*n*n
k=3*n*n+3*n+1
m=6*n+6
```

**Comment by nguyenthanhvuh** [comment]
DIG should be able to generate the later 3 easily.  For a[n]=n*n*n,  it won't be able to do that out of the box.  But you can just call a[n] a new variable,  e.g.,  v,  then you can get v=n*n*n.   

Also, from your traces, it's not possible to determine what `a[n]` is or means.

**Comment by TaihuLight** [comment]
After fixing the location of the function `printf()` in the C program, I can get a new trace file.  Meanwhile, I set `a[n]` as a new variable `an`. Then, DIG1 can get the expected results:
```
dig:Info:Detected 5 invs for Eqt:
    0: an - c == 0
    1: h - 96 == 0
    2: m - 6*n - 6 == 0
    3: 3*n^2 - k + 3*n + 1 == 0
    4: k*n - 3*c - k + 2*n + 1 == 0
Generated time: 3.390
```

**Comment by nguyenthanhvuh** [comment]
1. Glad that DIG can infer what you expected.
2. Yes I think you interpretation of the trace format is correct.  Notice there's no space in the array (just so that I can parse them more easily).

**Comment by TaihuLight** [comment]
Unfortunately, DIG1 cannot infer the nested array invariants. Because the error occurs when DIG1 infers invariants on the trace files  [https://github.com/unsat/dig/tree/dev/old/traces/AES_tosem/Nested](url).
```
dig_arrays:Info:Generate arr exps (nestings)
Traceback (most recent call last):
......
 File "/home/chengzi/workspace/dig1-dev/dig_miscs.py", line 1304, in _gt
    data=data)
  File "/home/chengzi/workspace/dig1-dev/dig_miscs.py", line 1328, in gen_root_trees
    for c in combs]
  File "/home/chengzi/workspace/dig1-dev/dig_miscs.py", line 1036, in __init__
    assert is_list(args.get('children')), args
AssertionError: {'commute': False, 'root': 'Alogtable', 'children': (<dig_miscs.Tree object at 0x7f3bba04a090>,)}
```
I am work hard to fix the bug, aiming to make DIG1 infer  the nested array invariants.

**Comment by nguyenthanhvuh** [comment]
this error is very easy to fix,  you can see right away the assertion is that it's expected children to be list,  but the given children is tuple  (<dig_miscs.Tree object at 0x7f3bba04a090>,).   Change that to list.

**Comment by TaihuLight** [comment]
I modified the program shown in https://github.com/unsat/dig/issues/23#issue-925508174, using a new scalar variable `tmp` to denote the array variable `a[n]`, in order to infer invariant for this program with the newer DIG3.
Unfortunately, it also occurs erros. How to modify the parameters in the function `mainQ()`? My aims are to transfer an array to 'a[]' and to make DIG3 work for infer invariants for this program.
```
void main(int argc, char **argv){
    mainQ(atoi(argv), atoi(argv[2]));
}
```

**Comment by nguyenthanhvuh** [comment]
My C code instrumentation is done in Ocaml/CIL  (see the ocaml/ dir in src/).  I think it will be tricky if you're not familiar with Ocaml and Cil.  The easiest way is you manually put in the tmp variable in the code yourself.   Also, DIG3 (more precisely, the symbolic execution tool used by DIG3) might not work well with arrays, so it might not work.   I think it's just easier to generate the trace file that just contain integer variable  (so tmp would be one of those variables) and use DIG3 to infer invariants from that trace file.

**Comment by TaihuLight** [comment]
Thank you. I will use generated trace file to generate invariants with DIG3.
For https://github.com/unsat/dig/issues/23#issuecomment-881139066, I try to fix it as following, (i.e., transform children to list)
```
class Tree(object):
    def __init__(self, args):     
        if is_dict(args) and 'coef' not in args and 'first_idx' not in args:
            ........
            if is_list(args.get('children')) is False:
                args['children']=[args.get('children')]                
            assert is_list(args.get('children')), args
```
The occurs is removed, but it cannot obtain valid invariants.
For the most trace files in the directory  `./AES_tosem/Nested/`, it output
```
dig_miscs:Debug:* gen_aexps [S,Si,r,w,Logtable,Alogtable]: 176 expressions generated
dig_arrays:Info:Apply reachability analysis to 176 nestings to find valid ones
dig_arrays:Info:Potential rels: 0
dig:Info:Refine 0 invs
refine:Debug:rfilter skips (|ps|=0, |tcs|=50)
dig:Info:Detected 0 invs for NestedArray:
Generated time: 1.513
```
It only can obtain nested array invarinat from `./AES_tosem/Nested/paper_nested_extvar.tcs`
```
dig_miscs:Debug:* gen_aexps [A,C,B]: 2 expressions generated
dig_arrays:Info:Apply reachability analysis to 2 nestings to find valid ones
dig_arrays:Debug:Nesting A[i1] == B[(i1)_] has 1 rel(s)
lambda A,B,i1: A[i1] == B[-2*i1 + 5]
dig_arrays:Debug:Nesting A[i1] == B[(i1)_] has 1 rel(s)
lambda A,B,i1: A[i1] == B[-2*i1 + 5]
dig_arrays:Info:Potential rels: 2
dig:Info:Refine 2 invs
refine:Debug:vset (before 2, after 1, diff 1)
refine:Debug:rfilter(|ps|=1, |tcs|=1)
dig:Info:Detected 1 invs for NestedArray:
    0: A[i1] == B[-2*i1 + 5]
Generated time: 0.086
```

**Comment by nguyenthanhvuh** [comment]
I looked around and found this file, which seems to be the result log of some previous run of DIG1: dig/old/traces/Results.  You can seem some of the inferred nested array.

Also, from quick glance from the output you have:  

```
dig_miscs:Debug:* gen_aexps [S,Si,r,w,Logtable,Alogtable]: 176 expressions generated
dig_arrays:Info:Apply reachability analysis to 176 nestings to find valid ones
dig_arrays:Info:Potential rels: 0
```

Something seems wrong about this because it generated too many expressions and also that reachability analysis was not able to find anything relations.  Probably there's a bug somewhere that cause this.

**Comment by TaihuLight** [comment]
# @

- [ ] 

1. 

- 

>

**Comment by TaihuLight** [comment]
I am very sad for this bug!
