### ISSUE TITLE
DIG does not terminate?

### ISSUE THREAD

**Issue by SWVM** [unsat/dig#25]
I built dig from the dockerfile.
When I test my installation with CohenDiv.java, the program took a long time to run. 

It has been running for an hour and is still running by the time I created this issue.
Is this an expected behavior?

below is the input/output (force quit after running for 3 hours)

```
root@2f4594d66a76:/dig/src# sage -python -O dig.py  ../tests/paper/CohenDiv.java -log 3
settings:INFO:2021-09-10 00:09:12.407921: dig.py ../tests/paper/CohenDiv.java -log 3
alg:INFO:analyze '../tests/paper/CohenDiv.java'
get symstates:running 24 jobs using 8 threads: [3, 3, 3, 3, 3, 3, 3, 3]
symstates exprs:running 66 jobs using 8 threads: [8, 8, 8, 8, 8, 8, 9, 9]
alg:INFO:compute symbolic states (61.68s)
alg:INFO:infer invs at 3 locs: vtrace0, vtrace2, vtrace1
get traces:running 9 jobs using 8 threads: [1, 1, 1, 1, 1, 1, 1, 2]
get traces:running 112 jobs using 8 threads: [14, 14, 14, 14, 14, 14, 14, 14]
find eqts:running 3 jobs using 3 threads: [1, 1, 1]
prove:running 5 jobs using 5 threads: [1, 1, 1, 1, 1]
prove:running 3 jobs using 3 threads: [1, 1, 1]
prove:running 8 jobs using 8 threads: [1, 1, 1, 1, 1, 1, 1, 1]
prove:running 5 jobs using 5 threads: [1, 1, 1, 1, 1]
prove:running 8 jobs using 8 threads: [1, 1, 1, 1, 1, 1, 1, 1]
prove:running 2 jobs using 2 threads: [1, 1]
prove:running 5 jobs using 5 threads: [1, 1, 1, 1, 1]
prove:running 7 jobs using 7 threads: [1, 1, 1, 1, 1, 1, 1]
prove:running 7 jobs using 7 threads: [1, 1, 1, 1, 1, 1, 1]
prove:running 3 jobs using 3 threads: [1, 1, 1]
prove:running 6 jobs using 6 threads: [1, 1, 1, 1, 1, 1]
prove:running 9 jobs using 8 threads: [1, 1, 1, 1, 1, 1, 1, 2]
prove:running 4 jobs using 4 threads: [1, 1, 1, 1]
prove:running 4 jobs using 4 threads: [1, 1, 1, 1]
^CTraceback (most recent call last):
  File "/dig/src/dig.py", line 239, in <module>
    dig.start(seed=seed, maxdeg=args.maxdeg)
  File "/dig/src/alg.py", line 135, in start
    self.infer(self.EQTS, dinvs, lambda: self.infer_eqts(maxdeg, dtraces, inps))
  File "/dig/src/alg.py", line 186, in infer
    new_invs = f()  # get invs
  File "/dig/src/alg.py", line 135, in <lambda>
    self.infer(self.EQTS, dinvs, lambda: self.infer_eqts(maxdeg, dtraces, inps))
  File "/dig/src/alg.py", line 205, in infer_eqts
    dinvs = solver.gen(auto_deg, dtraces, inps)
  File "/dig/src/infer/eqt.py", line 44, in gen
    wrs = CM.run_mp("find eqts", tasks, f, settings.DO_MP)
  File "/dig/src/helpers/vcommon.py", line 165, in run_mp
    rs = Q.get()
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
  File "src/cysignals/signals.pyx", line 320, in cysignals.signals.python_check_interrupt
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "src/cysignals/signals.pyx", line 320, in cysignals.signals.python_check_interrupt
KeyboardInterrupt

^Croot@2f4594d66a76:/dig/src# ^C
```

**Comment by SWVM** [comment]
There is no error message though, and the CPU/RAM usage are high.

**Comment by nguyenthanhvuh** [comment]
check with the latest version, should not have this issue.
